### ISSUE TITLE
xdot error in `drawTree`

### ISSUE THREAD

**Issue by Affie** [JuliaRobotics/IncrementalInference.jl#1043]
I got these errors on v0.18.0 with some local changes. I still need to look in more detail, but logging so long.
```
Error: <stdin>: syntax error in line 1 near '%'
Traceback (most recent call last):
  File "/usr/bin/xdot", line 4, in <module>
    main()
  File "/usr/lib/python3/dist-packages/xdot/__main__.py", line 77, in main
    win.open_file(inputfile)
  File "/usr/lib/python3/dist-packages/xdot/ui/window.py", line 668, in open_file
    self.set_dotcode(fp.read(), filename)
  File "/usr/lib/python3/dist-packages/xdot/ui/window.py", line 650, in set_dotcode
    if self.dotwidget.set_dotcode(dotcode, filename):
  File "/usr/lib/python3/dist-packages/xdot/ui/window.py", line 144, in set_dotcode
    if self._set_dotcode(dotcode, filename, center=center):
  File "/usr/lib/python3/dist-packages/xdot/ui/window.py", line 131, in _set_dotcode
    xdotcode = self.run_filter(dotcode)
  File "/usr/lib/python3/dist-packages/xdot/ui/window.py", line 119, in run_filter
    error = error.decode()
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xbb in position 303: invalid start byte
```

and 

```julia
julia> fg = generateCanonicalFG_lineStep(3);

julia> tree = resetBuildTree!(fg);

[ Info: Building Bayes net...
┌ Warning: Listing only one variable [:x0] for non-unary factor type GenericMarginal
└ @ IncrementalInference ~/.julia/dev/IncrementalInference/src/FactorGraph.jl:1114
[ Info: Staring the Bayes tree construction from Bayes net
[ Info: Bayes Tree Complete

julia> drawTree(tree)
Error: /tmp/caesar/random/bt_fd3d6bde.dot: syntax error in line 4 near '['
┌ Warning: ProcessFailedException(Base.Process[Process(`dot /tmp/caesar/random/bt_fd3d6bde.dot -T dot -o /tmp/caesar/random/bt_fd3d6bde.dot`, ProcessExited(1))])
└ @ IncrementalInference ~/.julia/dev/IncrementalInference/src/JunctionTree.jl:491
stacktrace() = Base.StackTraces.StackFrame[macro expansion at show.jl:641 [inlined], drawTree(::IncrementalInference.MetaBayesTree; show::Bool, suffix::String, filepath::String, xlabels::Dict{Int64,String}, dpi::Int64, viewerapp::String, imgs::Bool) at JunctionTree.jl:492, drawTree(::IncrementalInference.MetaBayesTree) at JunctionTree.jl:459, top-level scope at REPL[75]:1, include_string(::Function, ::Module, ::String, ::String) at loading.jl:1091, repleval(::Module, ::String, ::String) at repl.jl:105, (::VSCodeServer.var"#43#45"{Module,String,REPL.LineEditREPL,REPL.LineEdit.Prompt})() at repl.jl:84, with_logstate(::Function, ::Any) at logging.jl:408, with_logger at logging.jl:514 [inlined], (::VSCodeServer.var"#42#44"{Module,String,REPL.LineEditREPL,REPL.LineEdit.Prompt})() at repl.jl:83, #invokelatest#1 at essentials.jl:710 [inlined], invokelatest(::Any) at essentials.jl:709, macro expansion at eval.jl:27 [inlined], (::VSCodeServer.var"#56#57")() at task.jl:356]
```

**Comment by dehann** [comment]
Hi, just make sure you have `sudo apt-get install xdot`
